dataset:
    root: /code/auto_remaster/sandbox/imeanflow/_smoke/prepared
    num_workers: 0
    pin_memory: False

model:
    model_str: imfDiT_B_2
    cfg_beta: 1.0

training:
    log_per_step: 1
    checkpoint_per_epoch: 1

    num_epochs: 1
    batch_size: 4
    learning_rate: 0.0001
    warmup_epochs: 0

    adam_b2: 0.95
    ema_type: 'const'

    sample_per_epoch: 999
    fid_per_epoch: 1

    seed: 42

fid:
    device_batch_size: 1
    num_samples: 16
    cache_ref: /code/auto_remaster/sandbox/imeanflow/_smoke/prepared/imagenet_256_fid_stats.npz

sampling:
    num_steps: 1
    omega: 7.5
    t_min: 0.4
    t_max: 0.65

logging:
    use_wandb: False
    wandb_project: 'YOUR PROJECT'
    wandb_entity: 'YOUR ENTITY'
    wandb_tags:
        - YOUR TAGS
    wandb_notes: 'YOUR NOTES'

load_from: ''